Repository 2025-Capstone-Project-Barion/BackEnd, pull requests merged in 2025-04, with the labels that each got.

#24 Order crud/feat/#23
  build.gradle
  src/main/java/me/barion/capstoneprojectbarion/Entity/Category.java
  src/main/java/me/barion/capstoneprojectbarion/Entity/Order.java
  src/main/java/me/barion/capstoneprojectbarion/controller/OrderController.java
  src/main/java/me/barion/capstoneprojectbarion/dto/OrderDto.java
  src/main/java/me/barion/capstoneprojectbarion/repository/OrderRepository.java
  src/main/java/me/barion/capstoneprojectbarion/service/OrderService.java
  src/main/resources/data.sql
Labels: FEAT

#20 RDS 배포 테스트
  .github/workflows/gradle.yml
  .github/workflows/pr_checker.yml
  .gitignore
  build.gradle
  src/main/java/me/barion/capstoneprojectbarion/Entity/Category.java
  src/main/java/me/barion/capstoneprojectbarion/Entity/Employee.java
  src/main/java/me/barion/capstoneprojectbarion/Entity/Order.java
  src/main/java/me/barion/capstoneprojectbarion/Entity/Store.java
  src/main/java/me/barion/capstoneprojectbarion/config/SecurityConfig.java
  src/main/java/me/barion/capstoneprojectbarion/controller/CategoryController.java
  src/main/java/me/barion/capstoneprojectbarion/controller/EmployeeController.java
  src/main/java/me/barion/capstoneprojectbarion/controller/LoginController.java
  src/main/java/me/barion/capstoneprojectbarion/controller/OrderController.java
  src/main/java/me/barion/capstoneprojectbarion/controller/StoreController.java
  src/main/java/me/barion/capstoneprojectbarion/dto/CategoryDto.java
  src/main/java/me/barion/capstoneprojectbarion/dto/EmployeeDto.java
  src/main/java/me/barion/capstoneprojectbarion/dto/LoginRequestDto.java
  src/main/java/me/barion/capstoneprojectbarion/dto/OrderDto.java
  src/main/java/me/barion/capstoneprojectbarion/dto/StoreNameDto.java
  src/main/java/me/barion/capstoneprojectbarion/dto/StoreTypeDto.java
  src/main/java/me/barion/capstoneprojectbarion/repository/CategoryRepository.java
  src/main/java/me/barion/capstoneprojectbarion/repository/EmployeeRepository.java
  src/main/java/me/barion/capstoneprojectbarion/repository/OrderRepository.java
  src/main/java/me/barion/capstoneprojectbarion/repository/StoreRepository.java
  src/main/java/me/barion/capstoneprojectbarion/service/CategoryService.java
  src/main/java/me/barion/capstoneprojectbarion/service/EmployeeService.java
  src/main/java/me/barion/capstoneprojectbarion/service/LoginService.java
  src/main/java/me/barion/capstoneprojectbarion/service/OrderService.java
  src/main/java/me/barion/capstoneprojectbarion/service/StoreService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: FEAT

#25 #20 fix : 자동으로 중복 제거하고 실행
  .github/workflows/gradle.yml
Labels: bug

#26 자동배포 적용
  .github/workflows/gradle.yml
Labels: bug

#29 Feat/#28 sales
  src/main/java/me/barion/capstoneprojectbarion/Entity/Sales.java
  src/main/java/me/barion/capstoneprojectbarion/controller/SalesController.java
  src/main/java/me/barion/capstoneprojectbarion/dto/SalesDto.java
  src/main/java/me/barion/capstoneprojectbarion/repository/OrderRepository.java
  src/main/java/me/barion/capstoneprojectbarion/repository/SalesRepository.java
  src/main/java/me/barion/capstoneprojectbarion/service/SalesService.java
Labels: FEAT, 윤영

#31 [mod] SalesTable
  src/main/java/me/barion/capstoneprojectbarion/Entity/Sales.java
  src/main/java/me/barion/capstoneprojectbarion/controller/SalesController.java
  src/main/java/me/barion/capstoneprojectbarion/dto/SalesDto.java
  src/main/java/me/barion/capstoneprojectbarion/repository/SalesRepository.java
  src/main/java/me/barion/capstoneprojectbarion/service/SalesService.java
Labels: 윤영, MOD
